[theme]
primaryColor = "#003366"            # Navy Blue
backgroundColor = "#FFFFFF"         # White
secondaryBackgroundColor = "#F0F2F6" # Light Grey for secondary areas
textColor = "#000000"               # Default text color
font = "sans serif"                 # Basic font options are "sans serif", "serif", "monospace"
